### ISSUE TITLE
Core Feature Module

### ISSUE THREAD

**Issue by baesparza** [UTPL-Rank/UTPL-Rank-Web#28]
**Description**

Setup the core feature module

**Tasks**

- [ ] Create the module `CoreModule`,
- [ ] Import the `CoreModule` In the `AppModule`
- [ ] Create the authentication service `AuthenticationService` in the services sub-folder, and import it in the `CoreModule`.
- [ ] Create the academic areas service `AcademicAreasService` in the services sub-folder, and import it in the `CoreModule`.
- [ ] Create the guard `CanActivateLoginGuard` in the guards sub-folder, and import it in the `CoreModule`.
- [ ] Create the guard `CanActivateUnauthorizedGuard` in the guards sub-folder, and import it in the `CoreModule`.
- [ ] Create the guard `CanActivateDashboardGuard` in the guards sub-folder, and import it in the `CoreModule`.

**Additional context**

- **`CanActivateLoginGuard`:** Validate access to the login component. Only for non-signed users can visit this page, 
  - Signed in users that have the `isAdmin` attribute in the claims will be redirected to `/
  - Other signed in users will be redirected to `/no-autorizado`

- **`CanActivateUnauthorizedGuard`:** Only users that have sign in and doesn't have the `isAdmin` claim can access this route. 
  - Admin users will be redirected to the dashboard landing `/`

- **`CanActivateDashboardGuard`:** Validate access to the dashboard.
  - Only admin users can continue
  - Non-authorized users are redirected to `/no-autorizado`,
  - Non-signed in users will be redirected to `/ingresar`
