### ISSUE TITLE
Setup Dashboard Feature

### ISSUE THREAD

**Issue by baesparza** [UTPL-Rank/UTPL-Rank-Web#30]
**Description**

Setup feature module, routing, and lazy load. Also provide scaffold for the dashboard

**Tasks**

- [ ] Create routing module `DashboardRoutingModule ` with the pages attribute.
- [ ] Create the feature module `DashboardModule`, and import the routing module.
- [ ] Lazy load the `DashboardModule` in the `AppRoutingModule` with an empty path, add the `CanActivateDashboardGuard`.

- - - 

- [ ] Create the component `DashboardShellComponent` in the component sub-folder
- [ ] Add the `DashboardShellComponent` in the routing module with an empty path. Like the example below

**Additional context**

- The `CanActivateDashboardGuard` is already defined in the core module - #28

**Example**
```ts
const routes: Routes = [
  {
    path: '',
    component: DashboardShellComponent,
    children: [
      // ...
    ]
  },
];
```

**Comment by baesparza** [comment]
The tasks of this issue have been moved to #31
