### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by baesparza** [UTPL-Rank/UTPL-Rank-Web#31]
**Description**

Dashboard Home. This is the main page, were users land when signing in, or opening new page. Display analytics about the application

**Tasks**

- [ ] Create a component `HomeComponent` in the pages folder
- [ ] Add the component to the `DashboardRoutingModule` with the path empty
- [ ] TODO: add more tasks

**Additional context**

- The `DashboardRoutingModule` is already defined in the dashboard setup - #30
