### ISSUE TITLE
Setup Academic Areas Feature

### ISSUE THREAD

**Issue by baesparza** [UTPL-Rank/UTPL-Rank-Web#32]
**Description**

Setup feature module and routing.

**Tasks**

- [ ] Create routing module `AcademicAreasRoutingModule`.
- [ ] Create the feature module `AcademicAreasModule`, and import the routing module.
- [ ] Lazy load the `AcademicAreasModule` in the `DashboardRoutingModule` with the path `areas-academicas`

**Additional context**

- The module `DashboardRoutingModule` was defined at #30

**Comment by baesparza** [comment]
The task of this issue have been moved to #33
