### ISSUE TITLE
List Academic Areas

### ISSUE THREAD

**Issue by baesparza** [UTPL-Rank/UTPL-Rank-Web#33]
**Description**

Show all academic areas with stats of each area, support list grid view.

**Tasks**

- [ ] Create component `ListAcademicAreasComponent` in the pages subfolder
- [ ] Import the component `ListAcademicAreasComponent` in the ´AcademicAreasRoutingModule´ with the path empty to match the url `/areas-academicas`
- [ ] Support view all the `AcademicAreas` in real time thought the `AcademicAreasService`.

**Additional context**

- The `AcademicAreasRoutingModule` was created at #32 
- The `AcademicAreasService` service was defined at #28
