### ISSUE TITLE
View Academic Area Information

### ISSUE THREAD

**Issue by baesparza** [UTPL-Rank/UTPL-Rank-Web#34]
**Description**

Display all the information in real time about an academic area, and all the academic degrees related to this academic area. 

**Tasks**

- [ ] Create component `ViewAcademicAreaInformationComponent` in the pages sub-folder
- [ ] Create guard `ValidAcademicAreaIdGuard` to validate the `idArea` provided is valid thought the `AcademicAreasService` 
- [ ] Import the component `ViewAcademicAreaInformationComponent` in the ´AcademicAreasRoutingModule´ with the path `:idArea` to match the url `/areas-academicas/:idArea`, with the guard `ValidAcademicAreaIdGuard`.
- [ ] Support view academic area information in real time thought the `AcademicAreasService` 

**Additional context**

- The `AcademicAreasRoutingModule` was created at #32
- The `AcademicAreasService` service was defined at #28
