### ISSUE TITLE
Update Academic Area Information

### ISSUE THREAD

**Issue by baesparza** [UTPL-Rank/UTPL-Rank-Web#35]
**Description**

This page provides actions to update information about this academic area.

**Tasks**

- [ ] Create component `UpdateAcademicAreaInformationComponent` in the pages sub-folder
- [ ] Import the component ´UpdateAcademicAreaInformationComponent´ in the ´AcademicAreasRoutingModule´ with the path `:idArea/actualizar` to match the url `/areas-academicas/:idArea/actualizar`,
- [ ] Create resolver `PreloadAcademicAreaInformationResolver` in the resolver sub-folder to pre-load the information of an `AcademicArea` thought the `AcademicAreasService` .
- [ ] Add the resolver `PreloadAcademicAreaInformationResolver` to the route
- [ ] Add the guard `ValidAcademicAreaIdGuard` to the route

**Additional context**

- The guard `ValidAcademicAreaIdGuard` was created at #34
- The `AcademicAreasRoutingModule` was created at #32
- The `AcademicAreasService` service was defined at #28
