### ISSUE TITLE
Setup Academic Degrees Feature

### ISSUE THREAD

**Issue by baesparza** [UTPL-Rank/UTPL-Rank-Web#38]
**Description**

Setup academic degrees feature module and routing.

**Tasks**

- [ ] Create routing module `AcademicDegreesRoutingModule`.
- [ ] Create the feature module `AcademicDegreesModule`
- [ ] Lazy load the `AcademicDegreesModule` in the `DashboardRoutingModule` with the path `titulaciones`
- [ ] Create the service `AcademicDegreesService` in the services sub-folder

**Additional context**

- The module `DashboardRoutingModule` was defined at #30

**Comment by baesparza** [comment]
The task from this issue have been moved to #39
