### ISSUE TITLE
List Academic Degrees

### ISSUE THREAD

**Issue by baesparza** [UTPL-Rank/UTPL-Rank-Web#39]
**Description**

Quick list of all the academic degrees in a grid or list mode, with filters by name, and group by areas.

**Tasks**

- [ ] Create component `ListAcademicDegreesComponent` in pages sub-folder
- [ ] Import the component `ListAcademicDegreesComponent` in the `AcademicDegreesRoutingModule` with the path empty, match the url `/titulaciones`
- [ ] Support view all the `AcademicDegrees` in real time through the `AcademicDegreesService`
- [ ] Support filter by `area`, `knowledgeArea`
- [ ] Support order by `name`
- [ ] Support pagination

**Additional context**

ADD ANY OTHER CONTEXT OR SCREENSHOT ABOUT THE FEATURE HERE
