### ISSUE TITLE
Create Academic Degree

### ISSUE THREAD

**Issue by baesparza** [UTPL-Rank/UTPL-Rank-Web#40]
**Description**

Create a new Academic degree with the minimum information required for a new degree

**Tasks**

- [ ] Create Component `CreateAcademicDegreeComponent` in the pages sub-folder
- [ ] Import the component `CreateAcademicDegreeComponent` in the `AcademicDegreesRoutingModule` with  the path `nuevo`, to match the url `/titulaciones/nuevo`
- [ ] Create resolver `PreloadAllAcademicAreasResolver` in the resolvers sub-folder, and pre-load all the `AcademicAreas` through the `AcademicAreasService`
- [ ] Create resolver `PreloadAllKnowledgeAreasResolver` in the resolvers sub-folder, and pre-load all the `KnowledgeAreas` through the `KnowledgeAreasService`
- [ ] Add the resolvers `PreloadAllAcademicAreasResolver` $ `PreloadAllKnowledgeAreasResolver` to the route in the routing module.
- [ ] Support create a new academic degree with the minimum information `id`, `name`, `area`, `information` `knowledgeAreas`.
- [ ] Support generate `id` with the name, create an async validator through the `AcademicDegreesService`, an use it in the name control
- [ ] Support select various `KnowledgeAreas`, at least 3
- [ ] Support removing trailing spaces before and after `name`, `description`

**Additional context**

- The `KnowledgeAreasService` is defined in #13
- The `AcademicAreasService` is defined in #28
- The `AcademicDegreesRoutingModule` is defined in #38 
- The `AcademicDegreesService` is defined in #38
