### ISSUE TITLE
View Academic Degree Information

### ISSUE THREAD

**Issue by baesparza** [UTPL-Rank/UTPL-Rank-Web#41]
**Description**

HERE GOES A CLEAR AND CONCISE DESCRIPTION OF THE FEATURE

**Tasks**

- [ ] Create component `ViewAcademicDegreeInformationComponent` in the pages sub-folder
- [ ] Create guard `AcademicDegreeExistGuard` to validate a degree exist with the `degreeId` provided
- [ ] Import the component `ViewAcademicDegreeInformationComponent` in the `AcademicDegreeRoutingModule` with the path `:degreeId` to match the url `/titulaciones/:degreeId`
- [ ] add the guard `AcademicDegreeExistGuard` to the route
- [ ] Support view academic degree information in real time through the `AcademicDegreesService`
- [ ] Support view `KnowledgeAreas` information through the `KnowledgeAreasService`

**Additional context**

- The `KnowledgeAreasService` is defined in #13
- The `AcademicDegreesRoutingModule` is defined in #38 
- The `AcademicDegreesService` is defined in #38
