### ISSUE TITLE
Update Academic Degree information

### ISSUE THREAD

**Issue by baesparza** [UTPL-Rank/UTPL-Rank-Web#42]
**Description**

Update specific information about an academic degree, Also rename an academic area, achieve an area, or delete if possible

**Tasks**

- [ ] Create Component `UpdateAcademicDegreeInformationComponent` in the pages sub-folder
- [ ] Create resolver `PreloadAcademicDegreeInformationResolver` to load an academic degree before entering the route through the `AcademicDegreesService`
- [ ] Import component in the routing module `AcademicDegreeRoutingModule` with the path `:degreeId/actualizar` to match the url `/titulaciones/:degreeId/actualizar`.
- [ ] Add the guard `AcademicDegreeExistGuard` to the route.
- [ ] Add the resolver `PreloadAcademicDegreeInformationResolver` to the route

- [ ] Create component `UpdateInformationAcademicDegreeComponent` in the components sub-folder
- [ ] Import the component in the `AcademicDegreesModule`
- [ ] Support update `information`, `redirectUrl`, `admissionTestDuration`, `numberOfQuestions`, `degreeDuration`, `offeredCoupons`, `degreeTitle` in the `UpdateInformationAcademicDegreeComponent` through the `AcademicDegreesService`

**Additional context**

- The `AcademicDegreesModule` was defined at #38 
- The `AcademicDegreeRoutingModule` was defined at #38 
- The `AcademicDegreesService` was defined at #38 
- The guard `AcademicDegreeExistGuard` was created at #41
